name: Run Monthly Playlist on Last Day

on:
  schedule:
    - cron: '*/5 * * * *'   # At 23:59 on days 28-31

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run only if it's the last day of the month
        run: |
          python3 -c "import datetime; from datetime import datetime, timedelta; now = datetime.utcnow(); tomorrow = now + timedelta(days=1); exit(0) if now.month != tomorrow.month else exit(1)"
        continue-on-error: true
        id: check_date

      - name: Run playlist script
        if: steps.check_date.outcome == 'failure'  # Only run if the check step exited with 1
        env:
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_BASE64: ${{ secrets.SPOTIFY_BASE64 }}
          SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        run: python3 playlist.py
