name: Monthly Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 28-31 * *' # Run at 19:00 GST (15:00 UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check if it's the last day of the month
        id: check_date
        run: python3 -c "import datetime; now=datetime.datetime.utcnow(); tomorrow=now+datetime.timedelta(days=1); exit(1) if now.month != tomorrow.month else exit(0)"

      - name: Run playlist script
        #if: steps.check_date.outcome == 'failure'  # Only run if it's the last day
        env:
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_BASE64: ${{ secrets.SPOTIFY_BASE64 }}
          SPOTIFY_USER_ID: ${{ secrets.SPOTIFY_USER_ID }}
        run: python3 playlist.py
